In [1]:
# introduction to Python DataCamp

In [34]:
# create a list 
list_1 = [1, 2, 'f', '3', 23]
type(list_1)

list

In [35]:
# add something to a list
list_1_added = list_1 + ['d', 3]
list_1_added

[1, 2, 'f', '3', 23, 'd', 3]

In [36]:
# deleting from a list 
del(list_1[3])

In [37]:
# to add together two lists we can just sum them 
list_2 = ['dd', 'd']
list_overall = list_1 + list_2 
list_overall

[1, 2, 'f', 23, 'dd', 'd']

In [38]:
# list references (y это тот же лист, потому что мы сохранили ссылку на него)  
x = [1, 2, 3]
y = x 
y[1] = 'z'
y

[1, 'z', 3]

In [39]:
x

[1, 'z', 3]

In [40]:
# если нужно сделать отличающийся от x лист y 
y = list(x)
y = x[:]

In [41]:
# ';' sign is used to place commands on the same line
print('hello'); print('you')

hello
you


In [16]:
# some built in functions: 
print(round(2, 3))
print(max(1, 2))
print(min(1, 2))
type('dsf')

2
2
1


str

In [43]:
# call for function info 
help(round)
?max

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [44]:
import pandas as pd
help(pd.merge)

Help on function merge in module pandas.core.reshape.merge:

merge(left, right, how: str = 'inner', on=None, left_on=None, right_on=None, left_index: bool = False, right_index: bool = False, sort: bool = False, suffixes=('_x', '_y'), copy: bool = True, indicator: bool = False, validate=None) -> 'DataFrame'
    Merge DataFrame or named Series objects with a database-style join.
    
    The join is done on columns or indexes. If joining columns on
    columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
    on indexes or indexes on a column or columns, the index will be passed on.
    When performing a cross merge, no column specifications to merge on are
    allowed.
    
    Parameters
    ----------
    left : DataFrame
    right : DataFrame or named Series
        Object to merge with.
    how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
        Type of merge to be performed.
    
        * left: use only keys from left frame, similar to 

In [45]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [1]:
pow(2,2)
pow(3,3)

27

In [47]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [48]:
list_1 = [1, 2, 0, 1.2, 3, 2.3, 4]
sorted(list_1)

[0, 1, 1.2, 2, 2.3, 3, 4]

In [49]:
# iterable - any collection of objects
a = 1.74 # - this is an object. Methods are functions that belongs to objects

In [50]:
# to discover methods related to str objects 
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

In [ ]:
# lists, floats, integers, booleans and strings come packaged with methods

In [ ]:
# list methods. Most list methods will change the list they're called on
#list_1.append()
#list_1.remove()
#list_1.reverse()

In [51]:
from math import pi 

In [52]:
# lists are pretty powerful, they allow 
# - to hold different data types
# - change, add, remove

# but they don't allow to perform mathematical operations over collections - numpy array can do that 
# numpy array can only have one data type inside of it. Numpy Array has its own methods 

In [53]:
import numpy as np 
list_1 = [1, 2, 3, 4, 5]
list_2 = [2, 3, 6, 4, 2]

array_1 = np.array(list_1)
array_2 = np.array(list_2)

In [54]:
# add arrays 
array_1 + array_2

array([3, 5, 9, 8, 7])

In [55]:
# filter arrays
array_1[array_1 > 1]

array([2, 3, 4, 5])

In [56]:
x = ['a', 'b', 'c']
print(x[1])

np_x = np.array(x)
print(np_x[1])

b
b


In [57]:
# np.ndarray - number of dimensions array
type(np_x)

numpy.ndarray

In [58]:
np_2d = np.array([[1, 3, 3, 5, 9],
                [4, 5, 1, 4, 0]])
np_2d

array([[1, 3, 3, 5, 9],
       [4, 5, 1, 4, 0]])

In [59]:
# subsetting arrays
np_2d[0][3]

5

In [60]:
np_2d[0, 3]

5

In [61]:
# np_2d[rows, columns]

np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])